# Utilisation de Node.js 18
FROM node:22

# Définition du répertoire de travail
WORKDIR /app

# Copie des fichiers package.json et package-lock.json
COPY package*.json ./

# Installation des dépendances
RUN npm install

# Copie du reste du code source
COPY . .

# Exposer le port utilisé par l'API
EXPOSE 5200

# Démarrer l'API avec nodemon pour le hot reload
CMD ["npm", "run", "start:dev"]
