# Utilisation de Node.js 18
FROM node:22

# Définition du répertoire de travail
WORKDIR /app

# Copie des fichiers package.json et package-lock.json
COPY package*.json ./

# Installation des dépendances en mode production
RUN npm install --only=production

# Copie du reste du code source
COPY . .

# Exposer le port utilisé par l'API
EXPOSE 5300

# Démarrer l'API en mode production
CMD ["npm", "run", "start:prod"]