FROM node:22

WORKDIR /app

# Copier package.json et package-lock.json
COPY package*.json ./
RUN npm install

# Copier le reste des fichiers de l'application
COPY . .

# Exposer le port 5100
EXPOSE 5100

# Commande de démarrage
CMD ["npm", "run", "start:dev"]
